# Generated by Django 5.2.4 on 2025-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
